Repository AdrianKokot/put-reunice-platform, pull requests merged in 2023-08, with the labels that each got.

#14 ci: add deploy workflow
  .github/workflows/angular-build-and-test.yml
  .github/workflows/auto-deploy.yml
  Dockerfile
  backend/Dockerfile
  backend/src/main/java/com/example/cms/configuration/CustomApplicationConfiguration.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/example/cms/page/PageControllerTest.java
Labels: Deploy to dev

#15 ci: add check for main branch
  .github/workflows/auto-deploy.yml
Labels: Deploy to dev

#19 ci: load .env.example inside java workflow
  .github/workflows/java-build-and-test.yml
Labels: bug

#10 Implement language switcher
  frontend/modules/shared/ui/src/lib/layout/language-switcher/language-switcher.component.html
  frontend/modules/shared/ui/src/lib/layout/language-switcher/language-switcher.component.scss
  frontend/modules/shared/ui/src/lib/layout/language-switcher/language-switcher.component.spec.ts
  frontend/modules/shared/ui/src/lib/layout/language-switcher/language-switcher.component.ts
  frontend/modules/shared/ui/src/lib/layout/language-switcher/language.constant.ts
  frontend/modules/shared/ui/src/lib/layout/top-bar/top-bar.component.html
  frontend/modules/shared/ui/src/lib/layout/top-bar/top-bar.component.scss
  frontend/modules/shared/ui/src/lib/layout/top-bar/top-bar.component.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/assets/i18n/en.json
  frontend/src/index.html
Labels: enhancement

#32 fix: add sticky header where missing in admin tables
  frontend/modules/admin/src/lib/keyword/feature/keyword-list/keyword-list.component.html
  frontend/modules/admin/src/lib/page/feature/page-list/page-list.component.html
  frontend/modules/admin/src/lib/template/feature/template-list/template-list.component.html
  frontend/modules/admin/src/lib/university/feature/university-list/university-list.component.html
  frontend/modules/admin/src/lib/user/feature/user-list/user-list.component.html
Labels: bug

#31 Collapsable sidebar on mobile
  frontend/modules/shared/ui/src/lib/layout/sidebar/sidebar.component.html
  frontend/modules/shared/ui/src/lib/layout/sidebar/sidebar.component.ts
  frontend/modules/shared/ui/src/lib/layout/top-bar/top-bar.component.html
  frontend/modules/shared/ui/src/lib/ui.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/root.component.html
  frontend/src/app/root.component.less
  frontend/src/app/root.component.ts
Labels: enhancement

#48 Add profile page
  frontend/modules/admin/src/lib/page/feature/page-edit-form/page-edit-form.component.ts
  frontend/modules/shared/data-access/src/lib/services/backup.service.ts
  frontend/modules/shared/data-access/src/lib/services/file.service.ts
  frontend/modules/shared/security/src/lib/auth.service.ts
  frontend/modules/shared/ui/src/lib/layout/top-bar/top-bar.component.html
  frontend/modules/shared/util/src/index.ts
  frontend/modules/shared/util/src/lib/breadcrumb/breadcrumb.service.spec.ts
  frontend/modules/shared/util/src/lib/throw-error.ts
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/profile/feature/profile-change-password/profile-change-password.component.html
  frontend/src/app/profile/feature/profile-change-password/profile-change-password.component.spec.ts
  frontend/src/app/profile/feature/profile-change-password/profile-change-password.component.ts
  frontend/src/app/profile/feature/profile-form/profile-form.component.html
  frontend/src/app/profile/feature/profile-form/profile-form.component.spec.ts
  frontend/src/app/profile/feature/profile-form/profile-form.component.ts
  frontend/src/app/profile/feature/profile-shell/profile-shell.component.html
  frontend/src/app/profile/feature/profile-shell/profile-shell.component.spec.ts
  frontend/src/app/profile/feature/profile-shell/profile-shell.component.ts
  frontend/src/app/profile/profile.module.ts
  frontend/src/assets/i18n/en.json
  frontend/src/styles.less
  frontend/testing/src/index.ts
  frontend/testing/src/lib/authenticated-user.provider.ts
Labels: enhancement

#33 🚀 Add table filters
  frontend/modules/admin/src/lib/admin.style.less
  frontend/modules/admin/src/lib/dashboard/feature/dashboard-shell/dashboard-shell.component.ts
  frontend/modules/admin/src/lib/keyword/feature/keyword-list/keyword-list.component.html
  frontend/modules/admin/src/lib/page/feature/page-list/page-list.component.html
  frontend/modules/admin/src/lib/page/feature/page-list/page-list.component.ts
  frontend/modules/admin/src/lib/shared/base-table-imports.module.ts
  frontend/modules/admin/src/lib/shared/table/reunice-abstract-table.directive.ts
  frontend/modules/admin/src/lib/shared/table/table-filter/table-filter.component.html
  frontend/modules/admin/src/lib/shared/table/table-filter/table-filter.component.less
  frontend/modules/admin/src/lib/shared/table/table-filter/table-filter.component.spec.ts
  frontend/modules/admin/src/lib/shared/table/table-filter/table-filter.component.ts
  frontend/modules/admin/src/lib/shared/util/resource-search-wrapper.ts
  frontend/modules/admin/src/lib/template/feature/template-list/template-list.component.html
  frontend/modules/admin/src/lib/university/feature/university-list/university-list.component.html
  frontend/modules/admin/src/lib/university/feature/university-list/university-list.component.ts
  frontend/modules/admin/src/lib/user/feature/user-list/user-list.component.html
  frontend/modules/admin/src/lib/user/feature/user-list/user-list.component.ts
  frontend/modules/shared/data-access/src/lib/api.params.ts
  frontend/modules/shared/data-access/src/lib/services/abstract-api.service.ts
  frontend/modules/shared/data-access/src/lib/services/key-words.service.ts
  frontend/modules/shared/data-access/src/lib/services/template.service.ts
  frontend/modules/shared/data-access/src/lib/services/user.service.ts
  frontend/modules/shared/ui/src/lib/layout/sidebar/sidebar.component.ts
  frontend/src/assets/i18n/en.json
  frontend/src/styles.less
  frontend/testing/src/lib/authenticated-user.provider.ts
Labels: enhancement
